netspective-labs/sql-aide

- pattern/data-vault_test.ts
- pattern/enum-table_test.ts
- pattern/typical_test.ts
- render/dialect/pg/routine_test.ts
- render/domain/domain.ts
replace the type DATETIME to TIMESTAMP for supporting both sqlite and postgres
> fix: replace  DATETIME to TIMESTAMP

- examples/mssql-sqla-example.ts
- render/ddl/table/primary-key.ts
- render/domain/domain.ts
add MSSQL template for auto-increment primary key as IDENTITY(1,1) NOT NULL
add DATETIME2 and GETDATE 
add example for sql-server
> dev ms sql update

- render/dialect/pg/routine.ts
- render/dialect/pg/routine_test.ts
update PG routine with PL/Python and PL/Java
update routine test with  PL/Python and PL/Java options
> feat: update PG routine with PL/Python and PL/Java

- examples/jobs-mssql-sqla.ts
- examples/jobs-mssql-sqla_test.fixture-01.sql
- render/ddl/table/primary-key.ts
- render/dialect/pg/inspect.ts
update primary key handling for MS-SQL dialect
update test cases 
update MSSQL sample file
> Support auto Increment primary key for MSSQL[#23]

- examples/jobs-mssql-sqla.ts
- examples/jobs-mssql-sqla_test.fixture-01.sql
- render/domain/domain.ts
add varchar support
update mssql sample with foriegn key
update unit test SQL file
> chore: update for MSSQL varchar support [#25]

- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.puml
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
- pattern/infra-assurance/models_test.ts
Views added to Insfra Assurance models with test cases and fixtures
> feat:   infra assurance model views

- examples/jobs-mssql-sqla.ts
- examples/jobs-mssql-sqla_test.fixture-01.sql
- examples/jobs-mssql-sqla_test.ts
- render/ddl/view.ts
update view in jobs-mssql-sqla.ts file
update test fixture file
update text file to remove  new line character
> feat: support view for MSSQL [#45]

- lib/sql/pg/upsert.psql
update SELECT  query for finding  unique column keys
fix issues found in insert using conflict option
update file extension from .sql to .psql
> fix: update upsert sql query

- pattern/data-vault/data-vault.ts
add the option to the composite unique key for the  DataVault tables
> feat: add composite unique constraint to DV #52

- pattern/infra-assurance/governance.ts
- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.puml
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
- pattern/infra-assurance/models_test.ts
Updated sytem info model from infra assurance models
> chore: system info models

- lib/sql/pg/federated.psql
Federated SQL migration file added
> feat: pgsql federated sql migration

- lib/sql/pg/engine.psql
- lib/sql/pg/federated.psql
>  feat: pgsql engine sql migration

- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.puml
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
- pattern/infra-assurance/models_test.ts
Need to update the following models 
- boundary 
- securityIncidentResponseTeam
Old Models
```
export const boundary = gm.autoIncPkTable("boundary", {
boundary_id,
parent_boundary_id: selfRef(boundary_id).optional(),
boundary_nature_id: boundaryNature.references.code(),
name: text(),
description: textNullable(),
...gm.housekeeping.columns,
});
export const securityIncidentResponseTeam = gm.autoIncPkTable(
"security_incident_response_team",
{
security_incident_response_team_id: autoIncPK(),
training_subject_id: trainingSubject.references.code(),
person_id: person.references.person_id(),
organization_id: organization.references.organization_id(),
training_status_id: statusValues.references.code(),
attended_date: date(),
...gm.housekeeping.columns,
},
);
```
Updated Models 
```
export const …
```
> refactor: boundary, securityincidentresponseteam model updates

- pattern/data-vault/data-vault.ts
add composite unique keys option to the satellite table definition
> feat: update table definition options #52

- lib/sql/pg/context.psql
- lib/sql/pg/engine.psql
- lib/sql/pg/federated.psql
Modified variable replacement for multi line function
> variable replacement for multiline function

- examples/jobs-mssql-sqla.ts
- examples/jobs-mssql-sqla_test.fixture-01.sql
- examples/jobs-mssql-sqla_test.ts
- pattern/typical/enum-table.ts
- pattern/typical/enum-table_test.ts
- pattern/typical/typical.ts
- render/domain/domain.ts
- modified typical.ts and enum-table.ts to add varCharEnumTable
-  modified test cases
-  updated example class for jobs-mssql-sqla.ts and it's test fixture
> feat: new varCharEnumTable to support with NVARCHAR [#54]

- examples/data-vault-sqla_content_classification.ts
- examples/data-vault-sqla_content_classification_test.fixture.sql
- examples/data-vault-sqla_content_classification_test.ts
- add data vault for content classification
- add views to display results
- add stored functions/procedures
> feat: add datavault content classification #72

- examples/infra-assurance/ia-example.omc.sqla.fixture.sh
- examples/infra-assurance/ia-example.omc.sqla.fixture.sql
- examples/infra-assurance/ia-example.omc.sqla.ts
- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
- pattern/udm/README.md
- pattern/udm/governance.ts
- pattern/udm/mod.ts
- pattern/udm/models.ts
- pattern/udm/models_test.fixture.puml
- pattern/udm/models_test.fixture.sh
- pattern/udm/models_test.fixture.sql
- pattern/udm/models_test.ts
Interim UDM models added.
- Migrated infra assurance Universal Data Models to UDM folder.
- Fixed the `example/infra-assurance/ia-example.omc.sqla.ts` .
> feat: interim UDM models

- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
- pattern/infra-assurance/models_test.ts
- pattern/udm/models_test.fixture.sh
- pattern/udm/models_test.fixture.sql
- pattern/udm/models_test.ts
Date format updated to UTC in test cases
> fix: date format to UTC in test cases

- examples/infra-assurance/ia-example.omc.sqla.fixture.puml
- examples/infra-assurance/ia-example.omc.sqla.fixture.sh
- examples/infra-assurance/ia-example.omc.sqla.fixture.sql
- pattern/infra-assurance/models_test.fixture.puml
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
- pattern/infra-assurance/models_test.ts
- pattern/udm/models.ts
- pattern/udm/models_test.fixture.puml
- pattern/udm/models_test.fixture.sh
- pattern/udm/models_test.fixture.sql
- pattern/udm/models_test.ts
Fix for the parse error - foreign key mismatch
> fix: error in infra assurance test case

- support/docs-nextra/pages/getting-started/ungoverned/05-unwrapping-zod-types.md
- support/docs-nextra/pages/getting-started/ungoverned/06-zod-type-baggage.md
- support/docs-nextra/pages/getting-started/ungoverned/07-zod-schema-proxy.md
Added explanations to the example tutorials.
> feat: add explanations for new examples

- examples/getting-started/08-zod-table-pk-tmpl.sqla.ts
- support/docs-nextra/pages/getting-started/ungoverned/08-zod-table-pk-tmpl.md
- support/docs-nextra/pages/getting-started/ungoverned/_meta.json
I suggest that we add an example with `primary key`. 
There is a question about the order. Should we move it to the 3rd place and change the order of current examples? Or we keep it at it's current position?
> doc: add an example with PK

- examples/infra-assurance/ia-example.omc.sqla.fixture.puml
- examples/infra-assurance/ia-example.omc.sqla.fixture.sh
- examples/infra-assurance/ia-example.omc.sqla.fixture.sql
- examples/jobs-mssql/jobs-mssql-sqla_test.fixture-01.sql
- pattern/governed/governed_test.ts
- pattern/infra-assurance/models_test.fixture.puml
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
- pattern/typical/typical.ts
- pattern/typical/typical_test.ts
- pattern/udm/models.ts
- pattern/udm/models_test.fixture.puml
- pattern/udm/models_test.fixture.sh
- pattern/udm/models_test.fixture.sql
- render/domain/domain.ts
Update JSONB type for postgres dialect and TEXT for other dialects.
> chore: enhance housekeeping fields #97

- examples/jobs-mssql/jobs-mssql-sqla.ts
- examples/jobs-mssql/jobs-mssql-sqla_test.fixture-01.sql
Added modification based on housekeeping fields
updated test file also.
> chore: enhance audit fields in SQL example #97

- pattern/quality-system/models.ts
- pattern/quality-system/models_test.fixture.puml
- pattern/quality-system/models_test.fixture.sh
- pattern/quality-system/models_test.fixture.sql
- pattern/quality-system/models_test.ts
@shah  update models with comments for table and column
add test fixtures files
add the table data lineage
> feat: update quality system update #104

- support/docs-astro/astro.config.mjs
- support/docs-astro/package.json
Astro Starlight Update  for 
Older version: 0.3.0
New version: 0.4.0
> docs: starlight upgrade for SQLa Astro documentation  

- pattern/governed/governed.ts
- pattern/quality-system/models.ts
- pattern/quality-system/models_test.fixture.sh
- pattern/quality-system/models_test.fixture.sql
- render/domain/domain.ts
- render/domain/domains_test.ts
- Text array type added to domains.
- Removed the table comments section from quality-systems.
> chore: add text array type to domains

- examples/jobs-mssql/jobs-mssql-sqla.ts
- examples/jobs-mssql/jobs-mssql-sqla_test.fixture-01.sql
- render/ddl/view_test.ts
Added test case for namespaced view with type-safe columns specified 
updated MSSQL example with the namespace in safevViewDefn 
Updated test fixture for MSSQL example
> chore: add test case for safevViewDefn #120

- pattern/infra-assurance/models_test.ts
- pattern/udm/models_test.ts
Updated module test case in
- UDM
- NIA
> feat: module test case added in UDM and NIA #106

- render/domain/domain.ts
- render/domain/domain_test.ts
- Added the Boolean type as a domain.
> feat: add boolean as domain

- render/ddl/table/column.ts
- render/domain/domain.ts
- Added default option for boolean domain type.
- Updated defaultValue in the typical table column definition.
> feat: add default value to boolean domain type 

- pattern/typical/typical.ts
- render/ddl/table/table_test.ts
- render/dialect/pg/routine.ts
- render/domain/domain.ts
- render/domain/domain_test.ts
Set default value given to the domains like text, boolean, integer, float. Updated the default value for SP args as well.
> feat: set default value for various data type domains

- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.ts
- pattern/udm/models.ts
- pattern/udm/models_test.fixture.sh
- pattern/udm/models_test.ts
Updated typical.typicalCLI to sqliteCLI.typicalCLI in the following files
1. udm/models_test.ts
2. infra-assurance/models_test.ts
Removed the cli from 
1. udm/models.ts
2. infra-assurance/models.ts
> refactor: changed to sqliteCLI

- pattern/pgdcp/context.sqla.ts
- pattern/pgdcp/engine.sqla.ts
- pattern/pgdcp/mod.ts
- pattern/pgdcp/mod_test.ts
- pattern/pgdcp/pgdcp.ts
- pattern/pgdcp/shield.sqla.ts
- pattern/udm/models.ts
- render/dialect/pg/routine.ts
- Added pgdcp shield pattern.
- Updated pg routine to add privilege to stored function.
- Updated udm models.
> feat: pgdcp shield pattern

- pattern/governed/governed.ts
- pattern/observability/metrics.ts
- pattern/observability/mod_test.metrics-pg-fixture.sql
- pattern/observability/mod_test.metrics-sqlite-fixture.sql
- pattern/observability/mod_test.ts
- pattern/typical/typical.ts
- render/ddl/table/table.ts
- render/domain/domain.ts
- render/domain/domain_test.ts
add option for the 'after table definition'
update table definition for metric value
update stored procedure for inserting metric value update domain ZodNumber with Serial type
update test fixtures for observability
update unit test for domain
> feat: update observability model

- examples/infra-assurance/ia-example.omc.sqla.fixture.sh
- examples/infra-assurance/ia-example.omc.sqla.fixture.sql
- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
Some data are missing in the view due to foreign key mismatch. Updated changes in `infra-assurance/models`
> fix: view data missing changes

- pattern/udm/models.ts
- render/dialect/pg/trigger.ts
- render/dialect/pg/trigger_test.ts
- render/emit/sql.ts
- Initial setup for trigger DDL.
- Exported varchar domain types from UDM.
> feat: introduce trigger DDL

- pattern/pgdcp/mod.ts
- pattern/pgdcp/postgraphile.sqla.ts
- render/dialect/pg/trigger.ts
- render/dialect/pg/trigger_test.ts
- Parameterized the quote identifiers in triggers
- Fixed typo in Pgdcp postgraphile file.
> feat: parameterize quote identifiers in triggers

- pattern/pgdcp/engine.sqla.ts
- pattern/pgdcp/mod.ts
- pattern/pgdcp/pgdcp.ts
- pattern/udm/models.ts
- Updated the pgdcp engine pattern.
- Added pgtap extension
- Exported jsonb domain types from udm.
> feat: update pgdcp engine pattern

- pattern/governed/governed.ts
- pattern/typical/typical.ts
- render/domain/domain.ts
- render/domain/domain_test.ts
- Added float array as domain.
- Updated the test cases.
> feat: add float array as domain

- pattern/governed/governed_test.ts
- pattern/typical/typical_test.ts
- Updated test cases for governed and typical patterns for the new domain float array.
> test: update typical and governed test case

- lib/universal/merge.ts
Add a new utility function `safeMerge` that facilitates type-safe merging of objects while retaining their original types. This function can handle merging arrays and nested objects, providing a comprehensive solution for combining complex data structures.
> feat: add safeMerge utility function

- lib/sql/pg/inspect.psql
remove duplicate constraints 
format the code
> fix: remove duplicate constraints #145

- pattern/pgdcp/shield.sqla.ts
Updated pgdcp shield pattern to include table permissions
> feat: update pgdcp shield pattern

- lib/pre-process/psql/include_test.ts
- pattern/governed/governed.ts
- pattern/pgdcp/context.sqla.ts
- pattern/pgdcp/engine.sqla.ts
- pattern/pgdcp/event.sqla.ts
- pattern/pgdcp/graphql.sqla.ts
- pattern/pgdcp/infrastructure.sqla.ts
- pattern/pgdcp/shield.sqla.ts
- pattern/pgdcp/version.sqla.ts
- pattern/typical/typical.ts
- render/dialect/pg/trigger.ts
- render/dialect/pg/trigger_test.ts
- render/domain/domain.ts
- Fixed pgdcp files for isolating generated and executed SQL files.
- Fixed trigger drop feature.
> Fix for some pgdcp files & trigger drop feature

- pattern/pgdcp/context.sqla.ts
- pattern/pgdcp/federated.sqla.ts
- Fixed the issues in context and federated patterns related to execution contexts
> fix: pgdcp context & federated patterns

- examples/infra-assurance/ia-example.omc.sqla.fixture.puml
- examples/infra-assurance/ia-example.omc.sqla.fixture.sh
- examples/infra-assurance/ia-example.omc.sqla.fixture.sql
- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.puml
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
Based on the ticket #158 some changes made to existing model.
1. Created asset_service table.
2. Added 3 more fields in the asset mentioned in the ticket.
3. Created a view named asset_service_view.
> feat: enhance assets model with services #158

- examples/pg_openai/sqla_openai_general_prediction.ts
- examples/pg_openai/sqla_openai_general_prediction_test.fixture.sql
- examples/pg_openai/sqla_openai_general_prediction_test.ts
add OPENAI based content topics prediction using 'pg_openai'
> feat: add topics prediction using pg_openai #156

- lib/quality-system/governance/jsdoc/parser.ts
- lib/quality-system/governance/jsdoc/parser_test.fixture-fail.sql
- lib/quality-system/governance/jsdoc/parser_test.fixture.sql
- lib/quality-system/governance/jsdoc/parser_test.ts
Reading and interpreting JSDoc-style comments within the source code.
Extracting data governance, lineage, traceability, and code review details.
Creating structured JSON representations of the extracted data.
> feat: implement comment parsing for data governance

- pattern/postgres/deps.ts
- pattern/postgres/migrate.ts
- pattern/postgres/migrate_test.fixture.sql
- pattern/postgres/migrate_test.ts
- Created new pattern for SQL migration functionality in postgres.
> feat: pattern for migrate feature in postgres

- pattern/postgres/README.md
- pattern/postgres/migrate.ts
- pattern/postgres/migrate_test.fixture.sql
- pattern/postgres/migrate_test.ts
- Updated the migrate feature with transition  state changes.
- Updated test file and readme.
> Update ISLM migrate with transition state changes

- pattern/governed/governed.ts
- pattern/governed/governed_test.ts
- pattern/postgres/migrate.ts
- pattern/postgres/migrate_test.fixture.sql
- pattern/typical/typical.ts
- pattern/typical/typical_test.ts
- render/domain/domain.ts
- Added new textDefaultNullable domain in typical and governance.
- Updated the test cases.
> Add new textDefaultNullable schema object as domain to typical & governance

- pattern/postgres/README.md
- pattern/postgres/migrate.ts
- pattern/postgres/migrate_test.fixture.sql
- pattern/postgres/migrate_test.ts
- pattern/typical/state-table.ts
- pattern/typical/state-table_test.ts
- pattern/udm/models.ts
- Implementation of ISLM tables using the state tables.
- Updated state tables with unique column options.
> ISLM migration using state table typical pattern

- pattern/orchestration/duckdb/assurance.ts
- pattern/orchestration/duckdb/assurance_test-fixture-fail.csv
- pattern/orchestration/duckdb/assurance_test-fixture.duckdb.sql
- pattern/orchestration/duckdb/assurance_test.ts
- Added new rule requiredColumnNamesInTableStrict in structure assurance rules.
> feat: add new rule requiredColumnNamesInTableStrict in structure assurance rules

- pattern/orchestration/governance.ts
- pattern/orchestration/notebook.ts
- updated the orchestration session table in notebook with version details.
> feat: update orchsession table in notebook with version

- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.puml
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
- Created a new table named 'audit_service_type' to incorporate audit service type into the audit service.
- Converted all auto-incremented tables into textpk tables to utilize ULID as the primary key.
> feat: asset service type create #432

- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
- Updated the asset service view to include the asset type identifier and asset type name.
- Enhanced the person_skill_view by incorporating organization details for both the added party relation and person relation.
- Developed the person organization list view.
> refactor: person skills with respect to organization identifiers #192

- pattern/orchestration/duckdb/assurance.ts
- pattern/orchestration/duckdb/assurance_test-fixture.duckdb.sql
Did the implicit cast to varchar for SQL query in latest release of duckdb
> Implicit cast to varchar for SQL query in latest release of duckdb

- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.puml
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
Implemented database tables for the Human Resource Management System (HRMS), focusing on employee onboarding and offboarding functionalities.
> feat: add human resource management #196

- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.puml
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
This PR introduces a new model for managing termination checklist data. In addition to the model, a new view has been created to handle the display and interaction with this data.
> feat: termination checklist checklist model #196

- pattern/infra-assurance/models.ts
- pattern/infra-assurance/models_test.fixture.sh
- pattern/infra-assurance/models_test.fixture.sql
Created a view to list terminated employees
> feat: terminated employee list view #196

- render/ddl/table/index.ts
- render/ddl/table/table_test.ts
- Added the index type in table index
> Add index type in index generating DDL

- pattern/postgres/migrate.ts
- pattern/postgres/migrate_test.fixture.sql
- Updated the schema qualifier in the islm migrate function.
> Update the schema qualifier in the islm migrate function

- pattern/postgres/README.md
- pattern/postgres/migrate.ts
- pattern/postgres/migrate_test.fixture.sql
- pattern/postgres/migrate_test.ts
- removed search path & update the schema qualifier in islm migration.
> Remove search path & update the schema qualifier in islm migration

- pattern/postgres/migrate.ts
- pattern/postgres/migrate_test.fixture.sql
- Updated in islm migration procedure naming.
> Update in islm migration procedure naming

- pattern/postgres/migrate.ts
- pattern/postgres/migrate_test.fixture.sql
- fixed the ambiguity with the header body separator in ISLM migrate stored procedure
> Fix Header body separator in stored procedure
